// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBPneZZQHsbAJyAhz8n2YwNqV1ue0Tn4tg',
    appId: '1:597720652794:web:21e0bfd77addcd2d042243',
    messagingSenderId: '597720652794',
    projectId: 'heritage-8ad80',
    authDomain: 'heritage-8ad80.firebaseapp.com',
    storageBucket: 'heritage-8ad80.firebasestorage.app',
    measurementId: 'G-4TQN8PSJWK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDRshlGMBRpkspLIgTnz6a-sYzGkScZE3g',
    appId: '1:597720652794:android:f2e901e7135828b6042243',
    messagingSenderId: '597720652794',
    projectId: 'heritage-8ad80',
    storageBucket: 'heritage-8ad80.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD0QgVQQ_Wjxo0ktO1qAq1UxF2b_Lf3OgU',
    appId: '1:597720652794:ios:6797dd15495daa39042243',
    messagingSenderId: '597720652794',
    projectId: 'heritage-8ad80',
    storageBucket: 'heritage-8ad80.firebasestorage.app',
    iosBundleId: 'co.zw.coursehub',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD0QgVQQ_Wjxo0ktO1qAq1UxF2b_Lf3OgU',
    appId: '1:597720652794:ios:087b5375dd916fc4042243',
    messagingSenderId: '597720652794',
    projectId: 'heritage-8ad80',
    storageBucket: 'heritage-8ad80.firebasestorage.app',
    iosBundleId: 'com.example.coursehub',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBPneZZQHsbAJyAhz8n2YwNqV1ue0Tn4tg',
    appId: '1:597720652794:web:38af29c2ead803d2042243',
    messagingSenderId: '597720652794',
    projectId: 'heritage-8ad80',
    authDomain: 'heritage-8ad80.firebaseapp.com',
    storageBucket: 'heritage-8ad80.firebasestorage.app',
    measurementId: 'G-YG2HKDC8N8',
  );

}